import sharp from 'sharp'
import Version from './Version.js'

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
export const DEFAULT_MAX_WATERMARK_PIXELS = 4_000_000
let watermarkModulePromise
let watermarkLoadWarned = false
const logWarn = message => {
  if (globalThis.logger?.warn) globalThis.logger.warn(message)
  else console.warn(message)
}

const isPng = buffer => buffer.length >= 8 && buffer.subarray(0, 8).equals(PNG_SIGNATURE)

const toImageBuffer = image => {
  if (!image) return null
  if (Buffer.isBuffer(image)) return image
  if (image instanceof Uint8Array) return Buffer.from(image)
  if (typeof image === 'string') {
    const base64 = image.replace(/^base64:\/\//, '').replace(/^data:image\/\w+;base64,/, '')
    return Buffer.from(base64, 'base64')
  }
  return null
}

const getImagePayload = image => image?.file ?? image?.data?.file ?? image?.url ?? image?.data?.url ?? image

const setImagePayload = (image, payload) => {
  if (!image || Buffer.isBuffer(image) || typeof image === 'string') return segment.image(payload)
  if (Object.prototype.hasOwnProperty.call(image, 'file')) return { ...image, file: payload }
  if (image.data && Object.prototype.hasOwnProperty.call(image.data, 'file')) return { ...image, data: { ...image.data, file: payload } }
  return segment.image(payload)
}

const getWatermarkEncoder = async () => {
  try {
    watermarkModulePromise ||= import('@ikenxuan/watermark')
    const watermark = await watermarkModulePromise
    return watermark.embedWatermarkToPngBytes
  } catch (error) {
    watermarkModulePromise = null
    if (!watermarkLoadWarned) {
      watermarkLoadWarned = true
      logWarn(`[Render] 隐水印模块加载失败，已跳过隐水印: ${error instanceof Error ? error.message : String(error)}`)
    }
    return null
  }
}

export const buildWatermarkText = () => JSON.stringify({
  a: Date.now(),
  b: `Generated by ${Version.pluginName} v${Version.version}, with source code open-sourced under the GPL-3.0 license`,
  c: `Powered by ${Version.BotName} ${Version.BotVersion}`
})

/**
 * 将隐水印嵌入图片。输入非 PNG 时先转换为 PNG。
 * @param {Buffer|Uint8Array|string} image 图片数据
 * @param {string} watermarkText 水印文本
 * @param {{maxPixels?: number}} [options] 水印处理限制
 * @returns {Promise<Buffer|null>}
 */
export const embedWatermark = async (image, watermarkText, options = {}) => {
  const input = toImageBuffer(image)
  if (!input) return null
  try {
    const maxPixels = Number(options.maxPixels ?? DEFAULT_MAX_WATERMARK_PIXELS)
    const metadata = await sharp(input).metadata()
    const pixels = Number(metadata.width || 0) * Number(metadata.height || 0)
    if (maxPixels > 0 && pixels > maxPixels) {
      logWarn(`[Render] 图片 ${metadata.width}x${metadata.height} 超过隐水印安全上限，保留原图以避免内存峰值`)
      return null
    }

    const embedWatermarkToPngBytes = await getWatermarkEncoder()
    if (!embedWatermarkToPngBytes) return null
    const pngBuffer = isPng(input) ? input : await sharp(input).png().toBuffer()
    const result = embedWatermarkToPngBytes(pngBuffer, watermarkText)
    const output = result?.buffer ?? result
    if (Buffer.isBuffer(output)) return output
    return output instanceof Uint8Array ? Buffer.from(output) : null
  } catch (error) {
    logWarn(`[Render] 嵌入隐水印失败: ${error instanceof Error ? error.message : String(error)}`)
    return null
  }
}

/**
 * 对渲染后的图片消息数组应用隐水印。
 * @param {Array<*>|false} images 渲染输出
 * @param {string} watermarkText 水印文本
 * @returns {Promise<Array<*>|false>}
 */
export const applyWatermarkToImages = async (images, watermarkText) => {
  if (!Array.isArray(images)) return images
  for (const [index, image] of images.entries()) {
    const payload = getImagePayload(image)
    const watermarked = await embedWatermark(payload, watermarkText)
    if (watermarked) images[index] = setImagePayload(image, watermarked)
  }
  return images
}
